apiVersion: v1
kind: Pod
metadata:
  name: secret-pod1
  labels:
    app: secret-pod1
spec:
  containers:
    - name: secret-pod1
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh", "-c",  "env"]
      envFrom:
        - secretRef:
            name: mysecret
  restartPolicy: Never
