version: "2"
services:
  kibana7:
    image: docker.elastic.co/kibana/kibana:7.17.18
    container_name: kibana7
    volumes:
      - ./conf/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 15601:5601
    networks:
      - dev

networks:
  dev:
    external: true


volumes:
  data01:
    driver: local