# copy nginx默认配置
# docker run --rm --entrypoint=cat nginx /etc/nginx/nginx.conf > ./conf/nginx.conf

version: "2"
services:
  nginx-alpine318:
    image: nginx:alpine3.18-slim
    container_name: nginx-alpine318

    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    dns:
      - 8.8.8.8
    networks:
      - dev
networks:
  dev:
    external: true