version: '2'
services:
  xxl-job:
    image: xuxueli/xxl-job-admin:2.2.0
    container_name: xxl-job
    ports:
      - "18100:8080"
    environment:
      PARAMS: |
       --spring.datasource.url=jdbc:mysql://mysql8:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
       --spring.datasource.username=root 
       --spring.datasource.password=root
       --xxl.job.accessToken=

    dns:
      - 8.8.8.8
    networks:
      - default
      - dev


networks:
  dev:
    external:
      name: dev