version: '3'
services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.51.0
    volumes:
      - ./conf/prometheus-standalone.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 19090:9090
    dns:
      - 8.8.8.8
    networks:
      - default
      - dev
networks:
  dev:
    external:
      name: dev