---
# postgres配置
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: dev-ops
type: Opaque
data:
  # 123456
  POSTGRES_PASSWORD: 'MTIzNDU2Cg=='

#---
# 数据存储卷
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: ebs-pv-data-postgres
#  namespace: dev-ops
#spec:
#  capacity:
#    storage: 1Gi
#  volumeMode: Filesystem
#  accessModes:
#    - ReadWriteOnce
#  persistentVolumeReclaimPolicy: Retain
#  storageClassName: openebs-hostpath

---
# 无头服务
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: dev-ops
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
  clusterIP: None

---
# 有状态服务
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: dev-ops
  labels:
    name: postgres
spec:
  replicas: 1
  serviceName: postgres-svc
  selector:
    matchLabels:
      name: postgres
  template:
    metadata:
      name: postgres
      namespace: dev-ops
      labels:
        name: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: postgres-secret
          ports:
            - name: postgres
              containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgres
              name: ebs-pv-data-postgres
          startupProbe:
            tcpSocket:
              port: 5432
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 5
            timeoutSeconds: 1
  volumeClaimTemplates:
    - metadata:
        name: ebs-pv-data-postgres
      spec:
        accessModes: [ "ReadWriteOnce" ]
        volumeMode: Filesystem
        resources:
          requests:
            storage: 1Gi
        storageClassName: openebs-hostpath