# 容器活体探针
apiVersion: v1
kind: Pod
metadata:
  name: pod-http-get-lp
  labels:
    app: pod-http-get-lp
spec:
  containers:
    - name: pod-http-get-lp
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /_status/health
          port: 80
        # 启动容器后进行首次健康检查的等待时间,单位s
        initialDelaySeconds: 15
        # 健康检查发送请求后等待响应的超时时间,单位s
        timeoutSeconds: 1

