version: "2"
services:
  nacos:
    image: nacos/nacos-server:v2.0.3
    container_name: nacos-standalone
    env_file:
      - ./env/nacos-standlone-mysql.env
    #volumes:
      #- ./standalone-logs/:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
    dns:
      - 8.8.8.8
    networks:
      - dev
      - default
networks:
  dev:
    external:
      name: dev