version: "2"
services:
  mysql8:
    image: mysql:8.0.36
    container_name: mysql8
    
    environment:
      - MYSQL_ROOT_PASSWORD=root
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - .\\conf:/etc/mysql/conf.d
      - C:\\dev\\docker\\mysql8\\data:/var/lib/mysql
    ports:
      - 13104:3306
    networks:
      - dev
  adminer:
    image: adminer:4.8.1
    
    ports:
      - 13104:8080

networks:
  dev:
    external:
      name: dev