apiVersion: v1
kind: Pod
metadata:
  name: nfs-test-pod
  labels:
    app: nfs-test-pod
spec:
  containers:
    - name: nfs-test-pod
      image: nginx:stable-alpine
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: test-volume
          # 使用nfs的html覆盖掉容器内的目录
          mountPath: /usr/share/nginx/html
  restartPolicy: OnFailure
  volumes:
    - name: test-volume
      nfs:
        server: 192.168.217.128 # 网络存储服务地址
        path: /data/nfs/rw/nginx/html # 网络存储路径
        readOnly: false # 是否只读
