# 容器活体探针
apiVersion: v1
kind: Pod
metadata:
  name: pod-exec-lp
  labels:
    app: pod-exec-lp
spec:
  containers:
    - name: pod-exec-lp
      image: gcr.io/google_containers/busybox
      imagePullPolicy: IfNotPresent
      args:
        - /bin/sh
        - -c
        - echo ok > /tmp/health; sleep 10; rm -rf /tmp/health; sleep 600;
      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/health
        # 启动容器后进行首次健康检查的等待时间,单位s
        initialDelaySeconds: 15
        # 健康检查发送请求后等待响应的超时时间,单位s
        timeoutSeconds: 1

