apiVersion: v1
# 副本控制器
kind: ReplicationController
metadata:
  # rc的名称,全局唯一
  name: tomcat-demo-v3
spec:
  replicas: 1
  selector:
    app: tomcat-demo-v3
  template:
    metadata:
      labels:
        app: tomcat-demo-v3
    spec:
      affinity:
        # 节点亲和性
        podAffinity:
          # 必须满足
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: security
                    operator: In
                    values:
                      - S1
              topologyKey: kubernetes.io/hostname
        # 互斥
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - nginx
      containers:
        - name: tomcat-demo-v2
          image: tomcat
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: GET_HOSTS_FROM
              value: "dns"