apiVersion: v1
kind: Pod
metadata:
  name: nginx-init-containers
  labels:
    app: nginx-init-containers
spec:
  initContainers:
    - name: install
      image: busybox
      command:
        - wget
        - "-O"
        - "/work-dir/index.html"
        - http://kubernetes.io
      volumeMounts:
        - mountPath: "/work-dir"
          name: workdir
  containers:
    - name: nginx-init-containers
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: workdir
  restartPolicy: Always
  dnsPolicy: Default
  volumes:
    - name: workdir
      # 空目录卷(k8s默认分配的目录)
      emptyDir: {}
