apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-cloud-logging
  namespace: kube-system
  labels:
    app: fluentd-cloud-logging
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: fluentd-cloud-logging
  template:
    metadata:
      namespace: kube-system
      name: fluentd-cloud-logging
      labels:
        app: fluentd-cloud-logging
    spec:
      containers:
        - name: fluentd-cloud-logging
          image: gcr.io/google_containers/fluentd-elasticsearch:1.17
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
          env:
            - name: FLUENTD_ARGS
              value: "-q"
          volumeMounts:
            - mountPath: /var/lib/docker/containers
              name: containers
              readOnly: false
            - mountPath: /var/log
              name: varlog
              readOnly: false
      restartPolicy: Always
      volumes:
        - name: containers
          hostPath:
            path: /var/lib/docker/containers
        - name: varlog
          hostPath:
            path: /var/log

