# 获取Pod自身信息
apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod-container-vars
  labels:
    app: dapi-test-pod-container-vars
spec:
  containers:
    - name: dapi-test-pod-container-vars
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ["sh", "-c"]
      resources:
        requests:
          memory: "32Mi"
          cpu: "125m"
        limits:
          memory: "64Mi"
          cpu: "250m"
      env:
        - name: MY_CPU_REQUEST
          valueFrom:
            resourceFieldRef:
              containerName: dapi-test-pod-container-vars
              resource: requests.cpu
        - name: MY_MEM_REQUEST
          valueFrom:
            resourceFieldRef:
              resource: requests.memory
              containerName: dapi-test-pod-container-vars
  restartPolicy: Always
