apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mongo
  labels:
    type: pvc-mongo
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
