version: '2'
services:
  redis:
    image: redis:7.2.4-alpine
    container_name: redis
    ports:
      - 16379:6379
    restart: always
    dns:
      - 8.8.8.8
    # 如果需要进行配置密码相关,需要进行映射配置
    volumes:
      - .\\redis\\conf:/etc/redis/
      #- .\\redis\\data:/data
    command: ["redis-server", "/etc/redis/redis.conf"]