version: '2'
services:
  portainer-ce:
    # 默认密码: admin:admin1234567890
    container_name: portainer-ce
    image: portainer/portainer-ce:2.20.0
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    dns:
      - 8.8.8.8
    ports:
      - 19000:9000
    networks:
      - dev

volumes:
  portainer_data:
    driver: local

networks:
  dev:
    external: true