apiVersion: v1
kind: Pod
metadata:
  name: emptydir-pod
  labels:
    app: emptydir-pod
spec:
  containers:
    - name: emptydir-cv
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh", "-c",  "sleep 6000s"]
      volumeMounts:
        - mountPath: /cache
          name: cache-volume
    - name: emptydir-cd
      image: busybox
      imagePullPolicy: IfNotPresent
      command: [ "/bin/sh", "-c",  "sleep 6000s" ]
      volumeMounts:
        - mountPath: /test
          name: cache-volume
  restartPolicy: Never
  volumes:
    - name: cache-volume
      emptyDir: {}
