apiVersion: v1
kind: Pod
metadata:
  name: cm-default-test-app
  labels:
    app: cm-default-test-app
spec:
  containers:
    - name: cm-default-test-app
      image: kubeguide/tomcat-app:v1
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
      volumeMounts:
        - mountPath: /configfiles
          name: serverxml
  restartPolicy: Always
  volumes:
    - name: serverxml
      configMap:
        name: cm-appconfigfiles
        # items 不配置items这块的话默认以configmap的key

