apiVersion: v1
kind: Pod
metadata:
  name: cm-custom-test-app
  labels:
    app: cm-custom-test-app
spec:
  containers:
    - name: cm-custom-test-app
      image: kubeguide/tomcat-app:v1
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
      volumeMounts:
        - mountPath: /configfiles
          name: serverxml
  restartPolicy: Always
  volumes:
    - name: serverxml
      configMap:
        name: cm-appconfigfiles
        items:
          - key: key-serverxml
            path: server.xml
          - key: key-loggingproperties
            path: logging.properties

