apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-service-account-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: ClusterRole
  name: view   # 这里使用 view ClusterRole，该 ClusterRole 包含列举 Pods 的权限
  apiGroup: rbac.authorization.k8s.io
