apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: service-reader
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources:
      - services
      - endpoints
      - nodes
      - secrets
    verbs:
      - get
      - list
      - watch
      - create