apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-world-corn-job
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello-world-corn-job
              image: busybox
              args:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
  schedule: "*/1 * * * *"